version: "3"
services:
  app:
    build: ./app
    depends_on:
      - db
    links:
      - db
    expose:
      - 5000
    env_file:
      - ./app.env

  db:
    build: ./db
    env_file:
      - ./app.env

  server:
    build: ./server
    depends_on:
      - app
    ports:
      - "80:80"

# comment out this section if you don't want to run tests
  app-test:
    build: ./app
    command: ["sh", "-c", "sleep 30 && pytest -v"] # replace sleep with wait-for-it.sh
    depends_on:
      - app
      - db
    env_file:
      - ./app.env
